//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WeightForIt.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Meal
    {
        public Meal()
        {
            this.Consumptions = new HashSet<Consumption>();
        }
    
        public int MealId { get; set; }
        public string label { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public int UserId { get; set; }
    
        public virtual ICollection<Consumption> Consumptions { get; set; }
        public virtual UserProfile UserProfile { get; set; }
    }
}
