//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WeightForIt.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;
    
    public partial class Meal
    {
        public int MealId { get; set; }
        public int MenuId { get; set; }
        public int ProgramId { get; set; }

        public System.DateTime Date { get; set; }
    
        public virtual Menu Menu { get; set; }
        public virtual Program Program { get; set; }
    }
}
