//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region Métadonnées de relation EDM

[assembly: EdmRelationshipAttribute("WfiModel", "FK_Consumption_ToFood", "Food", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(WeightForIt.Models.Food), "Consumption", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(WeightForIt.Models.Consumption), true)]
[assembly: EdmRelationshipAttribute("WfiModel", "FK_Consumption_ToMeal", "Meal", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(WeightForIt.Models.Meal), "Consumption", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(WeightForIt.Models.Consumption), true)]
[assembly: EdmRelationshipAttribute("WfiModel", "FK_Meal_ToUserProfile", "UserProfile", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(WeightForIt.Models.UserProfile), "Meal", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(WeightForIt.Models.Meal), true)]
[assembly: EdmRelationshipAttribute("WfiModel", "FK_Program_ToUserProfile", "UserProfile", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(WeightForIt.Models.UserProfile), "Program", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(WeightForIt.Models.Program), true)]
[assembly: EdmRelationshipAttribute("WfiModel", "FK_Weight_ToUserProfile", "UserProfile", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(WeightForIt.Models.UserProfile), "Weight", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(WeightForIt.Models.Weight), true)]

#endregion

namespace WeightForIt.Models
{
    #region Contextes
    
    /// <summary>
    /// Aucune documentation sur les métadonnées n'est disponible.
    /// </summary>
    public partial class WfiEntities : ObjectContext
    {
        #region Constructeurs
    
        /// <summary>
        /// Initialise un nouvel objet WfiEntities à l'aide de la chaîne de connexion trouvée dans la section 'WfiEntities' du fichier de configuration d'application.
        /// </summary>
        public WfiEntities() : base("name=WfiEntities", "WfiEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialisez un nouvel objet WfiEntities.
        /// </summary>
        public WfiEntities(string connectionString) : base(connectionString, "WfiEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialisez un nouvel objet WfiEntities.
        /// </summary>
        public WfiEntities(EntityConnection connection) : base(connection, "WfiEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Méthodes partielles
    
        partial void OnContextCreated();
    
        #endregion
    
        #region Propriétés ObjectSet
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        public ObjectSet<Consumption> Consumptions
        {
            get
            {
                if ((_Consumptions == null))
                {
                    _Consumptions = base.CreateObjectSet<Consumption>("Consumptions");
                }
                return _Consumptions;
            }
        }
        private ObjectSet<Consumption> _Consumptions;
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        public ObjectSet<Food> Foods
        {
            get
            {
                if ((_Foods == null))
                {
                    _Foods = base.CreateObjectSet<Food>("Foods");
                }
                return _Foods;
            }
        }
        private ObjectSet<Food> _Foods;
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        public ObjectSet<Meal> Meals
        {
            get
            {
                if ((_Meals == null))
                {
                    _Meals = base.CreateObjectSet<Meal>("Meals");
                }
                return _Meals;
            }
        }
        private ObjectSet<Meal> _Meals;
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        public ObjectSet<Program> Programs
        {
            get
            {
                if ((_Programs == null))
                {
                    _Programs = base.CreateObjectSet<Program>("Programs");
                }
                return _Programs;
            }
        }
        private ObjectSet<Program> _Programs;
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        public ObjectSet<UserProfile> UserProfiles
        {
            get
            {
                if ((_UserProfiles == null))
                {
                    _UserProfiles = base.CreateObjectSet<UserProfile>("UserProfiles");
                }
                return _UserProfiles;
            }
        }
        private ObjectSet<UserProfile> _UserProfiles;
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        public ObjectSet<Weight> Weights
        {
            get
            {
                if ((_Weights == null))
                {
                    _Weights = base.CreateObjectSet<Weight>("Weights");
                }
                return _Weights;
            }
        }
        private ObjectSet<Weight> _Weights;

        #endregion

        #region Méthodes AddTo
    
        /// <summary>
        /// Méthode déconseillée pour ajouter un nouvel objet à l'EntitySet Consumptions. Utilisez la méthode .Add de la propriété ObjectSet&lt;T&gt; associée à la place.
        /// </summary>
        public void AddToConsumptions(Consumption consumption)
        {
            base.AddObject("Consumptions", consumption);
        }
    
        /// <summary>
        /// Méthode déconseillée pour ajouter un nouvel objet à l'EntitySet Foods. Utilisez la méthode .Add de la propriété ObjectSet&lt;T&gt; associée à la place.
        /// </summary>
        public void AddToFoods(Food food)
        {
            base.AddObject("Foods", food);
        }
    
        /// <summary>
        /// Méthode déconseillée pour ajouter un nouvel objet à l'EntitySet Meals. Utilisez la méthode .Add de la propriété ObjectSet&lt;T&gt; associée à la place.
        /// </summary>
        public void AddToMeals(Meal meal)
        {
            base.AddObject("Meals", meal);
        }
    
        /// <summary>
        /// Méthode déconseillée pour ajouter un nouvel objet à l'EntitySet Programs. Utilisez la méthode .Add de la propriété ObjectSet&lt;T&gt; associée à la place.
        /// </summary>
        public void AddToPrograms(Program program)
        {
            base.AddObject("Programs", program);
        }
    
        /// <summary>
        /// Méthode déconseillée pour ajouter un nouvel objet à l'EntitySet UserProfiles. Utilisez la méthode .Add de la propriété ObjectSet&lt;T&gt; associée à la place.
        /// </summary>
        public void AddToUserProfiles(UserProfile userProfile)
        {
            base.AddObject("UserProfiles", userProfile);
        }
    
        /// <summary>
        /// Méthode déconseillée pour ajouter un nouvel objet à l'EntitySet Weights. Utilisez la méthode .Add de la propriété ObjectSet&lt;T&gt; associée à la place.
        /// </summary>
        public void AddToWeights(Weight weight)
        {
            base.AddObject("Weights", weight);
        }

        #endregion

    }

    #endregion

    #region Entités
    
    /// <summary>
    /// Aucune documentation sur les métadonnées n'est disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="WfiModel", Name="Consumption")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Consumption : EntityObject
    {
        #region Méthode de fabrique
    
        /// <summary>
        /// Créez un nouvel objet Consumption.
        /// </summary>
        /// <param name="consumptionId">Valeur initiale de la propriété ConsumptionId.</param>
        /// <param name="foodId">Valeur initiale de la propriété FoodId.</param>
        /// <param name="mealId">Valeur initiale de la propriété MealId.</param>
        public static Consumption CreateConsumption(global::System.Int32 consumptionId, global::System.Int32 foodId, global::System.Int32 mealId)
        {
            Consumption consumption = new Consumption();
            consumption.ConsumptionId = consumptionId;
            consumption.FoodId = foodId;
            consumption.MealId = mealId;
            return consumption;
        }

        #endregion

        #region Propriétés simples
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ConsumptionId
        {
            get
            {
                return _ConsumptionId;
            }
            set
            {
                if (_ConsumptionId != value)
                {
                    OnConsumptionIdChanging(value);
                    ReportPropertyChanging("ConsumptionId");
                    _ConsumptionId = StructuralObject.SetValidValue(value, "ConsumptionId");
                    ReportPropertyChanged("ConsumptionId");
                    OnConsumptionIdChanged();
                }
            }
        }
        private global::System.Int32 _ConsumptionId;
        partial void OnConsumptionIdChanging(global::System.Int32 value);
        partial void OnConsumptionIdChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> quantity
        {
            get
            {
                return _quantity;
            }
            set
            {
                OnquantityChanging(value);
                ReportPropertyChanging("quantity");
                _quantity = StructuralObject.SetValidValue(value, "quantity");
                ReportPropertyChanged("quantity");
                OnquantityChanged();
            }
        }
        private Nullable<global::System.Int32> _quantity;
        partial void OnquantityChanging(Nullable<global::System.Int32> value);
        partial void OnquantityChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 FoodId
        {
            get
            {
                return _FoodId;
            }
            set
            {
                OnFoodIdChanging(value);
                ReportPropertyChanging("FoodId");
                _FoodId = StructuralObject.SetValidValue(value, "FoodId");
                ReportPropertyChanged("FoodId");
                OnFoodIdChanged();
            }
        }
        private global::System.Int32 _FoodId;
        partial void OnFoodIdChanging(global::System.Int32 value);
        partial void OnFoodIdChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 MealId
        {
            get
            {
                return _MealId;
            }
            set
            {
                OnMealIdChanging(value);
                ReportPropertyChanging("MealId");
                _MealId = StructuralObject.SetValidValue(value, "MealId");
                ReportPropertyChanged("MealId");
                OnMealIdChanged();
            }
        }
        private global::System.Int32 _MealId;
        partial void OnMealIdChanging(global::System.Int32 value);
        partial void OnMealIdChanged();

        #endregion

        #region Propriétés de navigation
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("WfiModel", "FK_Consumption_ToFood", "Food")]
        public Food Food
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Food>("WfiModel.FK_Consumption_ToFood", "Food").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Food>("WfiModel.FK_Consumption_ToFood", "Food").Value = value;
            }
        }
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Food> FoodReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Food>("WfiModel.FK_Consumption_ToFood", "Food");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Food>("WfiModel.FK_Consumption_ToFood", "Food", value);
                }
            }
        }
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("WfiModel", "FK_Consumption_ToMeal", "Meal")]
        public Meal Meal
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Meal>("WfiModel.FK_Consumption_ToMeal", "Meal").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Meal>("WfiModel.FK_Consumption_ToMeal", "Meal").Value = value;
            }
        }
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Meal> MealReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Meal>("WfiModel.FK_Consumption_ToMeal", "Meal");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Meal>("WfiModel.FK_Consumption_ToMeal", "Meal", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// Aucune documentation sur les métadonnées n'est disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="WfiModel", Name="Food")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Food : EntityObject
    {
        #region Méthode de fabrique
    
        /// <summary>
        /// Créez un nouvel objet Food.
        /// </summary>
        /// <param name="foodId">Valeur initiale de la propriété FoodId.</param>
        /// <param name="unit">Valeur initiale de la propriété unit.</param>
        /// <param name="calories">Valeur initiale de la propriété calories.</param>
        /// <param name="proteins">Valeur initiale de la propriété proteins.</param>
        /// <param name="glucides">Valeur initiale de la propriété glucides.</param>
        /// <param name="lipids">Valeur initiale de la propriété lipids.</param>
        public static Food CreateFood(global::System.Int32 foodId, global::System.Int32 unit, global::System.Int32 calories, global::System.Int32 proteins, global::System.Int32 glucides, global::System.Int32 lipids)
        {
            Food food = new Food();
            food.FoodId = foodId;
            food.unit = unit;
            food.calories = calories;
            food.proteins = proteins;
            food.glucides = glucides;
            food.lipids = lipids;
            return food;
        }

        #endregion

        #region Propriétés simples
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 FoodId
        {
            get
            {
                return _FoodId;
            }
            set
            {
                if (_FoodId != value)
                {
                    OnFoodIdChanging(value);
                    ReportPropertyChanging("FoodId");
                    _FoodId = StructuralObject.SetValidValue(value, "FoodId");
                    ReportPropertyChanged("FoodId");
                    OnFoodIdChanged();
                }
            }
        }
        private global::System.Int32 _FoodId;
        partial void OnFoodIdChanging(global::System.Int32 value);
        partial void OnFoodIdChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String RefValue
        {
            get
            {
                return _RefValue;
            }
            set
            {
                OnRefValueChanging(value);
                ReportPropertyChanging("RefValue");
                _RefValue = StructuralObject.SetValidValue(value, true, "RefValue");
                ReportPropertyChanged("RefValue");
                OnRefValueChanged();
            }
        }
        private global::System.String _RefValue;
        partial void OnRefValueChanging(global::System.String value);
        partial void OnRefValueChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 unit
        {
            get
            {
                return _unit;
            }
            set
            {
                OnunitChanging(value);
                ReportPropertyChanging("unit");
                _unit = StructuralObject.SetValidValue(value, "unit");
                ReportPropertyChanged("unit");
                OnunitChanged();
            }
        }
        private global::System.Int32 _unit;
        partial void OnunitChanging(global::System.Int32 value);
        partial void OnunitChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 calories
        {
            get
            {
                return _calories;
            }
            set
            {
                OncaloriesChanging(value);
                ReportPropertyChanging("calories");
                _calories = StructuralObject.SetValidValue(value, "calories");
                ReportPropertyChanged("calories");
                OncaloriesChanged();
            }
        }
        private global::System.Int32 _calories;
        partial void OncaloriesChanging(global::System.Int32 value);
        partial void OncaloriesChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 proteins
        {
            get
            {
                return _proteins;
            }
            set
            {
                OnproteinsChanging(value);
                ReportPropertyChanging("proteins");
                _proteins = StructuralObject.SetValidValue(value, "proteins");
                ReportPropertyChanged("proteins");
                OnproteinsChanged();
            }
        }
        private global::System.Int32 _proteins;
        partial void OnproteinsChanging(global::System.Int32 value);
        partial void OnproteinsChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 glucides
        {
            get
            {
                return _glucides;
            }
            set
            {
                OnglucidesChanging(value);
                ReportPropertyChanging("glucides");
                _glucides = StructuralObject.SetValidValue(value, "glucides");
                ReportPropertyChanged("glucides");
                OnglucidesChanged();
            }
        }
        private global::System.Int32 _glucides;
        partial void OnglucidesChanging(global::System.Int32 value);
        partial void OnglucidesChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 lipids
        {
            get
            {
                return _lipids;
            }
            set
            {
                OnlipidsChanging(value);
                ReportPropertyChanging("lipids");
                _lipids = StructuralObject.SetValidValue(value, "lipids");
                ReportPropertyChanged("lipids");
                OnlipidsChanged();
            }
        }
        private global::System.Int32 _lipids;
        partial void OnlipidsChanging(global::System.Int32 value);
        partial void OnlipidsChanged();

        #endregion

        #region Propriétés de navigation
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("WfiModel", "FK_Consumption_ToFood", "Consumption")]
        public EntityCollection<Consumption> Consumptions
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Consumption>("WfiModel.FK_Consumption_ToFood", "Consumption");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Consumption>("WfiModel.FK_Consumption_ToFood", "Consumption", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// Aucune documentation sur les métadonnées n'est disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="WfiModel", Name="Meal")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Meal : EntityObject
    {
        #region Méthode de fabrique
    
        /// <summary>
        /// Créez un nouvel objet Meal.
        /// </summary>
        /// <param name="mealId">Valeur initiale de la propriété MealId.</param>
        /// <param name="userId">Valeur initiale de la propriété UserId.</param>
        public static Meal CreateMeal(global::System.Int32 mealId, global::System.Int32 userId)
        {
            Meal meal = new Meal();
            meal.MealId = mealId;
            meal.UserId = userId;
            return meal;
        }

        #endregion

        #region Propriétés simples
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 MealId
        {
            get
            {
                return _MealId;
            }
            set
            {
                if (_MealId != value)
                {
                    OnMealIdChanging(value);
                    ReportPropertyChanging("MealId");
                    _MealId = StructuralObject.SetValidValue(value, "MealId");
                    ReportPropertyChanged("MealId");
                    OnMealIdChanged();
                }
            }
        }
        private global::System.Int32 _MealId;
        partial void OnMealIdChanging(global::System.Int32 value);
        partial void OnMealIdChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String label
        {
            get
            {
                return _label;
            }
            set
            {
                OnlabelChanging(value);
                ReportPropertyChanging("label");
                _label = StructuralObject.SetValidValue(value, true, "label");
                ReportPropertyChanged("label");
                OnlabelChanged();
            }
        }
        private global::System.String _label;
        partial void OnlabelChanging(global::System.String value);
        partial void OnlabelChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> Date
        {
            get
            {
                return _Date;
            }
            set
            {
                OnDateChanging(value);
                ReportPropertyChanging("Date");
                _Date = StructuralObject.SetValidValue(value, "Date");
                ReportPropertyChanged("Date");
                OnDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _Date;
        partial void OnDateChanging(Nullable<global::System.DateTime> value);
        partial void OnDateChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 UserId
        {
            get
            {
                return _UserId;
            }
            set
            {
                OnUserIdChanging(value);
                ReportPropertyChanging("UserId");
                _UserId = StructuralObject.SetValidValue(value, "UserId");
                ReportPropertyChanged("UserId");
                OnUserIdChanged();
            }
        }
        private global::System.Int32 _UserId;
        partial void OnUserIdChanging(global::System.Int32 value);
        partial void OnUserIdChanged();

        #endregion

        #region Propriétés de navigation
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("WfiModel", "FK_Consumption_ToMeal", "Consumption")]
        public EntityCollection<Consumption> Consumptions
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Consumption>("WfiModel.FK_Consumption_ToMeal", "Consumption");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Consumption>("WfiModel.FK_Consumption_ToMeal", "Consumption", value);
                }
            }
        }
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("WfiModel", "FK_Meal_ToUserProfile", "UserProfile")]
        public UserProfile UserProfile
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<UserProfile>("WfiModel.FK_Meal_ToUserProfile", "UserProfile").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<UserProfile>("WfiModel.FK_Meal_ToUserProfile", "UserProfile").Value = value;
            }
        }
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<UserProfile> UserProfileReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<UserProfile>("WfiModel.FK_Meal_ToUserProfile", "UserProfile");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<UserProfile>("WfiModel.FK_Meal_ToUserProfile", "UserProfile", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// Aucune documentation sur les métadonnées n'est disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="WfiModel", Name="Program")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Program : EntityObject
    {
        #region Méthode de fabrique
    
        /// <summary>
        /// Créez un nouvel objet Program.
        /// </summary>
        /// <param name="programId">Valeur initiale de la propriété ProgramId.</param>
        /// <param name="privacy">Valeur initiale de la propriété privacy.</param>
        /// <param name="userId">Valeur initiale de la propriété UserId.</param>
        public static Program CreateProgram(global::System.Int32 programId, global::System.Byte privacy, global::System.Int32 userId)
        {
            Program program = new Program();
            program.ProgramId = programId;
            program.privacy = privacy;
            program.UserId = userId;
            return program;
        }

        #endregion

        #region Propriétés simples
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ProgramId
        {
            get
            {
                return _ProgramId;
            }
            set
            {
                if (_ProgramId != value)
                {
                    OnProgramIdChanging(value);
                    ReportPropertyChanging("ProgramId");
                    _ProgramId = StructuralObject.SetValidValue(value, "ProgramId");
                    ReportPropertyChanged("ProgramId");
                    OnProgramIdChanged();
                }
            }
        }
        private global::System.Int32 _ProgramId;
        partial void OnProgramIdChanging(global::System.Int32 value);
        partial void OnProgramIdChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String objective
        {
            get
            {
                return _objective;
            }
            set
            {
                OnobjectiveChanging(value);
                ReportPropertyChanging("objective");
                _objective = StructuralObject.SetValidValue(value, true, "objective");
                ReportPropertyChanged("objective");
                OnobjectiveChanged();
            }
        }
        private global::System.String _objective;
        partial void OnobjectiveChanging(global::System.String value);
        partial void OnobjectiveChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> StartDate
        {
            get
            {
                return _StartDate;
            }
            set
            {
                OnStartDateChanging(value);
                ReportPropertyChanging("StartDate");
                _StartDate = StructuralObject.SetValidValue(value, "StartDate");
                ReportPropertyChanged("StartDate");
                OnStartDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _StartDate;
        partial void OnStartDateChanging(Nullable<global::System.DateTime> value);
        partial void OnStartDateChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Byte privacy
        {
            get
            {
                return _privacy;
            }
            set
            {
                OnprivacyChanging(value);
                ReportPropertyChanging("privacy");
                _privacy = StructuralObject.SetValidValue(value, "privacy");
                ReportPropertyChanged("privacy");
                OnprivacyChanged();
            }
        }
        private global::System.Byte _privacy;
        partial void OnprivacyChanging(global::System.Byte value);
        partial void OnprivacyChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 UserId
        {
            get
            {
                return _UserId;
            }
            set
            {
                OnUserIdChanging(value);
                ReportPropertyChanging("UserId");
                _UserId = StructuralObject.SetValidValue(value, "UserId");
                ReportPropertyChanged("UserId");
                OnUserIdChanged();
            }
        }
        private global::System.Int32 _UserId;
        partial void OnUserIdChanging(global::System.Int32 value);
        partial void OnUserIdChanged();

        #endregion

        #region Propriétés de navigation
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("WfiModel", "FK_Program_ToUserProfile", "UserProfile")]
        public UserProfile UserProfile
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<UserProfile>("WfiModel.FK_Program_ToUserProfile", "UserProfile").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<UserProfile>("WfiModel.FK_Program_ToUserProfile", "UserProfile").Value = value;
            }
        }
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<UserProfile> UserProfileReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<UserProfile>("WfiModel.FK_Program_ToUserProfile", "UserProfile");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<UserProfile>("WfiModel.FK_Program_ToUserProfile", "UserProfile", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// Aucune documentation sur les métadonnées n'est disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="WfiModel", Name="UserProfile")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class UserProfile : EntityObject
    {
        #region Méthode de fabrique
    
        /// <summary>
        /// Créez un nouvel objet UserProfile.
        /// </summary>
        /// <param name="userId">Valeur initiale de la propriété UserId.</param>
        /// <param name="userName">Valeur initiale de la propriété UserName.</param>
        public static UserProfile CreateUserProfile(global::System.Int32 userId, global::System.String userName)
        {
            UserProfile userProfile = new UserProfile();
            userProfile.UserId = userId;
            userProfile.UserName = userName;
            return userProfile;
        }

        #endregion

        #region Propriétés simples
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 UserId
        {
            get
            {
                return _UserId;
            }
            set
            {
                if (_UserId != value)
                {
                    OnUserIdChanging(value);
                    ReportPropertyChanging("UserId");
                    _UserId = StructuralObject.SetValidValue(value, "UserId");
                    ReportPropertyChanged("UserId");
                    OnUserIdChanged();
                }
            }
        }
        private global::System.Int32 _UserId;
        partial void OnUserIdChanging(global::System.Int32 value);
        partial void OnUserIdChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String UserName
        {
            get
            {
                return _UserName;
            }
            set
            {
                OnUserNameChanging(value);
                ReportPropertyChanging("UserName");
                _UserName = StructuralObject.SetValidValue(value, false, "UserName");
                ReportPropertyChanged("UserName");
                OnUserNameChanged();
            }
        }
        private global::System.String _UserName;
        partial void OnUserNameChanging(global::System.String value);
        partial void OnUserNameChanged();

        #endregion

        #region Propriétés de navigation
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("WfiModel", "FK_Meal_ToUserProfile", "Meal")]
        public EntityCollection<Meal> Meals
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Meal>("WfiModel.FK_Meal_ToUserProfile", "Meal");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Meal>("WfiModel.FK_Meal_ToUserProfile", "Meal", value);
                }
            }
        }
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("WfiModel", "FK_Program_ToUserProfile", "Program")]
        public EntityCollection<Program> Programs
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Program>("WfiModel.FK_Program_ToUserProfile", "Program");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Program>("WfiModel.FK_Program_ToUserProfile", "Program", value);
                }
            }
        }
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("WfiModel", "FK_Weight_ToUserProfile", "Weight")]
        public EntityCollection<Weight> Weights
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Weight>("WfiModel.FK_Weight_ToUserProfile", "Weight");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Weight>("WfiModel.FK_Weight_ToUserProfile", "Weight", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// Aucune documentation sur les métadonnées n'est disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="WfiModel", Name="Weight")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Weight : EntityObject
    {
        #region Méthode de fabrique
    
        /// <summary>
        /// Créez un nouvel objet Weight.
        /// </summary>
        /// <param name="weightId">Valeur initiale de la propriété WeightId.</param>
        /// <param name="date">Valeur initiale de la propriété date.</param>
        public static Weight CreateWeight(global::System.Int32 weightId, global::System.DateTime date)
        {
            Weight weight = new Weight();
            weight.WeightId = weightId;
            weight.date = date;
            return weight;
        }

        #endregion

        #region Propriétés simples
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 WeightId
        {
            get
            {
                return _WeightId;
            }
            set
            {
                if (_WeightId != value)
                {
                    OnWeightIdChanging(value);
                    ReportPropertyChanging("WeightId");
                    _WeightId = StructuralObject.SetValidValue(value, "WeightId");
                    ReportPropertyChanged("WeightId");
                    OnWeightIdChanged();
                }
            }
        }
        private global::System.Int32 _WeightId;
        partial void OnWeightIdChanging(global::System.Int32 value);
        partial void OnWeightIdChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> weight1
        {
            get
            {
                return _weight1;
            }
            set
            {
                Onweight1Changing(value);
                ReportPropertyChanging("weight1");
                _weight1 = StructuralObject.SetValidValue(value, "weight1");
                ReportPropertyChanged("weight1");
                Onweight1Changed();
            }
        }
        private Nullable<global::System.Double> _weight1;
        partial void Onweight1Changing(Nullable<global::System.Double> value);
        partial void Onweight1Changed();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> UserId
        {
            get
            {
                return _UserId;
            }
            set
            {
                OnUserIdChanging(value);
                ReportPropertyChanging("UserId");
                _UserId = StructuralObject.SetValidValue(value, "UserId");
                ReportPropertyChanged("UserId");
                OnUserIdChanged();
            }
        }
        private Nullable<global::System.Int32> _UserId;
        partial void OnUserIdChanging(Nullable<global::System.Int32> value);
        partial void OnUserIdChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime date
        {
            get
            {
                return _date;
            }
            set
            {
                OndateChanging(value);
                ReportPropertyChanging("date");
                _date = StructuralObject.SetValidValue(value, "date");
                ReportPropertyChanged("date");
                OndateChanged();
            }
        }
        private global::System.DateTime _date;
        partial void OndateChanging(global::System.DateTime value);
        partial void OndateChanged();

        #endregion

        #region Propriétés de navigation
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("WfiModel", "FK_Weight_ToUserProfile", "UserProfile")]
        public UserProfile UserProfile
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<UserProfile>("WfiModel.FK_Weight_ToUserProfile", "UserProfile").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<UserProfile>("WfiModel.FK_Weight_ToUserProfile", "UserProfile").Value = value;
            }
        }
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<UserProfile> UserProfileReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<UserProfile>("WfiModel.FK_Weight_ToUserProfile", "UserProfile");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<UserProfile>("WfiModel.FK_Weight_ToUserProfile", "UserProfile", value);
                }
            }
        }

        #endregion

    }

    #endregion

}
